### ISSUE TITLE
Documentation, build instructions from source

### ISSUE THREAD

**Issue by juandarr** [Goodwy/PlayBooks#12]
Hi Goodwy, 
first of all, let me say thank you for the development of such a great app. It is one of the best ones I have found that gives us the freedom to play and manage our audio books while having a good experience. 
Now to the point of the issue, is this repository the only place from which I can get access to the latest source code and better documentation about how to build the APK from source? I have been trying to build the app from source without success for several hours. I tried with/and without updating the Android Gradle Plugin, getting different kind of errors each time. For instance, this is the error I get when trying to build the app without any modification of the defaults, here is a [screenshot](https://ibb.co/dt3TRKB).
I am using Android Studio Bumblebee 2021.1.1 on Arch Linux. If you have any idea about what to do please let me know. 

Given that the project is FOSS, it would be great to offer better documentation so people can join you improving the software or get ideas from it to create their own programs. I understand you may be busy doing other stuff, but wanted to mentioned this since what happened to me could happen to other people, investing lots of hours to make the app work and then the frustration could turn them away. That being said, thanks again for the amazing work. I am planning to use the app on a regular basis, cheers!

**Comment by Goodwy** [comment]
Hello. Today posted the latest current version. Try to download it and just open it in android studio, I'm using the latest stable version. I work on Windows, maybe Linux needs some more settings, but I never used it.

**Comment by juandarr** [comment]
That's awesome. With the new commit I was able to build the app from source using the latest version of Android Studio for Linux (Bumblebee 2021.1.1), so thank you very much.  I took a quick look to the code and it certainly improved a lot since the last commit, probably because there are a ton of commits in between since you said that you work from a different git service provider.
I have been using the app for a week now and I like it a lot (just bought it and left a review on the App Store), used it mainly to listen to the second half of Dune and will use it to listen to many more books in the future. I would love to keep in touch with the project, do you have something like a website, or somewhere to follow the development? In any case, I will be looking at the code so maybe you will hear from me in the future, in the mean time, good luck with everything :D
